### PR TITLE
Use signed certificate in IngressControllers

### LINKED ISSUE #63: Ingress Controller provisioned with an invalid certificate
**Describe the bug**
The Ingress Controller created in the Kubernetes Cluster is provisioned with an invalid certificate.

**To Reproduce**
```typescript
import * as ct from "@cloud-toolkit/cloud-toolkit-aws";
const cluster = new Cluster("test-cluster");
```

**Expected behavior**
I can access to the exposed Ingress with a valid SSL Certificate.

**Actual behavior**
The Ingress Controller is using a self-signed SSL Certificate.

### PR DESCRIPTION
**Pull request by pasqualet**
**What type of PR is this?**

/kind bug
/kind feature

**What this PR does / why we need it**

Use signed certificate in IngressControllers.

**Which issue(s) this PR fixes**
Fixes #63 

**Does this PR introduce a user-facing change?**

```release-note
Add Certificate component
Kubernetes Cluster expose IngressControllers with signed certificate
```

### CODE REVIEW

File: provider/cmd/pulumi-resource-cloud-toolkit-aws/commons/certificate.ts [hunk 1]
```diff
@@ -0,0 +1,145 @@
...
+import defaultsDeep from "lodash.defaultsdeep";
+import {
+  CertificateArgs,
+  certificateDefaultArgs,
+} from "./certificateArgs";
+
+export { CertificateArgs };
+
+/**
+ * Certificate is a component that manages the Lubernetes addons to setup a production-ready cluster.
```
Comment (RedwineOS) [inline provider/cmd/pulumi-resource-cloud-toolkit-aws/commons/certificate.ts:12]: Lubernetes -> Kubernetes

**Review by RedwineOS — DISMISSED** [review]

**Review by RedwineOS — APPROVED** [review]
